markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Zivi Weinstock
url: http://zivi.github.io
description: A blog tracking my journey into coding.
twitter: z1v1
github: zivi
gravatar_url: http://www.gravatar.com/avatar/e611d793e989eae0853a75d524be7ab8.png
